Announcing Scala.js 1.3.0.
scala-js/scala-js-website pull request #518
Opened 2020-10-15 12:57 UTC by sjrd

2020-10-15 15:32 UTC, sjrd commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +#### For different entry points
IMO this should come first. That use case is entirely usefully satisfied by Scala.js core. The "many small modules" use case is useful only when piped through a bundler down the line.

2020-10-15 15:32 UTC, sjrd commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +Set the `moduleID` for your top level exports and/or module initializers explicitly.
Perhaps we should add
```suggestion
Set the `moduleID` for your top level exports and/or module initializers explicitly (a module initializer is basically a main method for the module).
```

2020-10-15 15:32 UTC, sjrd commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +Scala.js generated code has two different kinds of entry points:
I believe this should be spelled "Scala.js-generated code", with a dash, shouldn't it?

2020-10-15 15:32 UTC, sjrd commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +Set the `moduleID` for your top level exports and/or module initializers explicitly.
Also I think we spell "top-level exports" with a dash in "top-level", don't we?

2020-10-15 15:32 UTC, sjrd commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +* Module initializers: Code that gets executed when a module is imported.
```suggestion
* Module initializers: Code that gets executed when a module is imported (i.e., main methods).
```
?

2020-10-15 15:32 UTC, sjrd commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +#### `SmallestModules`
It might be good to add a sentence saying why this can be useful? (i.e., to speed up incremental bundling if the output is fed to downstream tooling)

2020-10-15 15:57 UTC, gzm0 commented
Yes to all your comments. I'll review the rest tomorrow morning.

2020-10-16 08:03 UTC, gzm0 reviewed
Only minor stuff.

2020-10-16 08:03 UTC, gzm0 commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +* [#4188](https://github.com/scala-js/scala-js/issues/4188) Make `js.Promise.then` return `js.Promise` instead of `js.Thenable`
This is a potentially source incompatible change. Shall we point this out?

2020-10-16 08:39 UTC, sjrd commented
Thanks for the review. I've added two commits, one addressing my review and one addressing yours. If LGTY I'll squash everything together before merging.

2020-10-16 08:41 UTC, gzm0 requested changes
Only nits.

2020-10-16 08:41 UTC, gzm0 commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +You can then create different entry points or generate as many small modules as possible using the following setups.
"and/or" to make it clear these compose?

2020-10-16 08:41 UTC, gzm0 commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +In incremental builds, they will not need to reparse the entire Scala.js-generated .js file, but instead only the small modules that have changed.
`s/reparse/reprocess/`?

2020-10-16 08:41 UTC, gzm0 commented on _posts/news/2020-10-16-announcing-scalajs-1.3.0.md
> +It might cause compilation error in some rare cases due to type inference, or if you declare a subclass of `js.Promise`.
`errors`

2020-10-16 08:43 UTC, sjrd commented
> Only nits.

Fixed and squashed :)

2020-10-16 08:46 UTC, gzm0 approved these changes

2020-10-16 08:47 UTC, merged