Announcing Scala.js 1.5.1.
scala-js/scala-js-website pull request #541
Opened 2021-03-31 12:38 UTC by sjrd

2021-03-31 18:11 UTC, gzm0 requested changes

2021-03-31 18:11 UTC, gzm0 commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +From Scala.js 1.5.0, which was a **minor** release:
I do not understand this fragment here.

2021-03-31 18:51 UTC, sjrd commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +From Scala.js 1.5.0, which was a **minor** release:
Ah, I copy-pasted that from the 1.3.1 announcement. It's supposed to mean that this section is "inherited" from the release notes 1.5.0.

Perhaps instead

> In addition, like Scala.js 1.5.0:

?

Or just remove that section?

2021-03-31 19:45 UTC, gzm0 approved these changes

2021-03-31 19:45 UTC, gzm0 commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +From Scala.js 1.5.0, which was a **minor** release:
I think there is value in keeping that section, because it makes the release notes stand on their own: They define the compatibility guarantees w.r.t. any Scala.js version. "In addition, like Scala.js 1.5.0:" is good IMO.

2021-03-31 19:45 UTC, gzm0 commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +* It is *not* entirely backward source compatible: it is not guaranteed that a codebase will compile *as is* when upgrading from 1.4.x or earlier (in particular in the presence of `-Xfatal-warnings`)
If you put "In addition, like Scala.js 1.5.0:", maybe add "... backward source compatible with 1.4.x:" to be more explicit.

2021-03-31 20:26 UTC, sjrd commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +* It is *not* entirely backward source compatible: it is not guaranteed that a codebase will compile *as is* when upgrading from 1.4.x or earlier (in particular in the presence of `-Xfatal-warnings`)
Good point :)

2021-04-01 06:05 UTC, gzm0 approved these changes

2021-04-01 07:54 UTC, merged

2021-04-03 07:13 UTC, tarsa commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +Among others, the following bugs have been fixed in 1.5.0:
Why does it mention 1.5.0 in release notes for 1.5.1?

2021-04-03 13:55 UTC, gzm0 commented on _posts/news/2021-04-01-announcing-scalajs-1.5.1.md
> +Among others, the following bugs have been fixed in 1.5.0:
Because it is a typo. (fix #542).