Fix the permalink for 1.5.1
scala-js/scala-js-website pull request #582
Opened 2022-08-02 14:52 UTC by blakehawkins

This is the URI referenced in https://github.com/scala-js/scala-js-website/blob/main/doc/internals/version-history.md

2022-08-03 13:22 UTC, gzm0 commented
TY for the PR. I'm assigning this to @sjrd, because I'm not 100% familiar with how these links are used / generated (I'd like to avoid removing an existing, incorrect permalink accidentally).

2022-08-03 14:44 UTC, sjrd requested changes
Please add an appropriate redirect in
https://github.com/scala-js/scala-js-website/blob/main/.htaccess
in order not to break existing links elsewhere.

2022-08-03 22:07 UTC, blakehawkins commented
The existing link is already a 404 so I think this PR doesn't actually add any exposure as-is

I'm happy to add a permalink redirect in any fase

2022-08-04 05:30 UTC, sjrd commented
The existing URL https://www.scala-js.org/news/2020/11/16/announcing-scalajs-1.5.1/ is clearly not a 404. So if we move that page, we do need a redirect. 😉

2022-08-04 05:31 UTC, sjrd approved these changes

2022-08-04 05:32 UTC, merged

2022-08-04 10:11 UTC, blakehawkins commented
Yeah fair enough, assuming someone managed to get to that URI!

2022-08-04 10:39 UTC, gzm0 commented
It's very likely in a tweet somewhere :))